package com.cwjitsu.app.service

import android.content.Intent
import android.net.Uri
import androidx.media3.common.AudioAttributes as MediaAudioAttributes
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.session.MediaSession
import androidx.media3.session.MediaSessionService
import com.cwjitsu.app.CWJitsuApp
import com.cwjitsu.app.R
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.launch

/**
 * Foreground MediaSessionService that surfaces the practice session as a
 * system media session, so the user can play/pause from the notification,
 * the lock screen, and Bluetooth/headset transport buttons.
 *
 * The actual practice audio (Morse + spoken answers) is generated by
 * [com.cwjitsu.app.audio.CwAudioEngine], driven by the app-wide
 * [SessionOrchestrator] - NOT by this ExoPlayer. The ExoPlayer plays a
 * short, silent, looping clip purely as a "carrier": Media3 needs a real
 * Player to host the session, post the notification, and receive transport
 * buttons, and the carrier keeps that machinery alive while a session runs.
 *
 * Control flow is a single loop with the orchestrator as source of truth:
 *  - orchestrator state  ->  carrier playWhenReady   (mirrored by the collector)
 *  - transport button    ->  carrier playWhenReady   (Media3 default commands)
 *                        ->  orchestrator.resume()/pause()  (the Player.Listener)
 * orchestrator.resume()/pause() are idempotent, so the mirror never fights
 * the listener.
 */
@UnstableApi
class PlaybackService : MediaSessionService() {

    private var player: ExoPlayer? = null
    private var session: MediaSession? = null
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main)

    private val app: CWJitsuApp get() = application as CWJitsuApp

    override fun onCreate() {
        super.onCreate()
        val audioAttrs = MediaAudioAttributes.Builder()
            .setUsage(C.USAGE_MEDIA)
            .setContentType(C.AUDIO_CONTENT_TYPE_SONIFICATION)
            .build()
        val ep = ExoPlayer.Builder(this).build().apply {
            // The carrier is silent and must not grab audio focus - the
            // real practice audio (engine + TTS) manages its own output.
            setAudioAttributes(audioAttrs, /* handleAudioFocus = */ false)
            volume = 0f
            repeatMode = Player.REPEAT_MODE_ONE
            playWhenReady = false
        }
        ep.addListener(object : Player.Listener {
            override fun onPlayWhenReadyChanged(playWhenReady: Boolean, reason: Int) {
                // A transport button (notification / Bluetooth / lock screen)
                // toggles the carrier; forward that to the orchestrator. Both
                // calls no-op when the state already matches, so our own
                // mirroring writes below don't loop back.
                if (playWhenReady) app.orchestrator.resume() else app.orchestrator.pause()
            }
        })
        player = ep
        session = MediaSession.Builder(this, ep)
            .setCallback(PlaybackCallback())
            .build()

        // Mirror the orchestrator's state onto the carrier so the media
        // session reflects what the practice session is actually doing.
        scope.launch {
            combine(app.orchestrator.runnerState, app.orchestrator.paused) { state, paused ->
                state to paused
            }.collect { (state, paused) ->
                val p = player ?: return@collect
                if (state == SessionOrchestrator.RunnerState.RUNNING) {
                    ensureCarrierLoaded(p)
                    p.playWhenReady = !paused
                } else {
                    // Session ended: drop the carrier so the notification
                    // goes away rather than lingering as a dead "paused".
                    p.playWhenReady = false
                    p.clearMediaItems()
                }
            }
        }
    }

    private fun ensureCarrierLoaded(p: ExoPlayer) {
        if (p.mediaItemCount > 0) return
        val item = MediaItem.Builder()
            .setUri("android.resource://$packageName/${R.raw.silence}")
            .setMediaMetadata(
                MediaMetadata.Builder()
                    .setTitle("CW Jitsu")
                    .setArtist("Morse practice")
                    // App icon as the notification / lock-screen artwork.
                    .setArtworkUri(
                        Uri.parse("android.resource://$packageName/${R.drawable.cwjicon}")
                    )
                    .build()
            )
            .build()
        p.setMediaItem(item)
        p.prepare()
    }

    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession? = session

    override fun onTaskRemoved(rootIntent: Intent?) {
        // If nothing is playing, let the service go when the task is swiped.
        if (player?.playWhenReady != true) stopSelf()
    }

    override fun onDestroy() {
        scope.cancel()
        session?.release()
        player?.release()
        session = null
        player = null
        super.onDestroy()
    }
}

/**
 * Minimal MediaSession.Callback so the session accepts controllers. Media
 * button events (notification, Bluetooth, lock screen) arrive as the default
 * play/pause player commands and are handled on the carrier's Player.Listener.
 */
@UnstableApi
class PlaybackCallback : MediaSession.Callback {
    override fun onConnect(
        session: MediaSession,
        controller: MediaSession.ControllerInfo,
    ): MediaSession.ConnectionResult {
        return MediaSession.ConnectionResult.accept(
            MediaSession.ConnectionResult.DEFAULT_SESSION_COMMANDS,
            MediaSession.ConnectionResult.DEFAULT_PLAYER_COMMANDS,
        )
    }
}
