package com.cwjitsu.app.service

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.media3.common.AudioAttributes as MediaAudioAttributes
import androidx.media3.common.C
import androidx.media3.common.ForwardingPlayer
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.session.CommandButton
import androidx.media3.session.MediaSession
import androidx.media3.session.MediaSessionService
import androidx.media3.session.SessionCommand
import androidx.media3.session.SessionResult
import com.cwjitsu.app.CWJitsuApp
import com.cwjitsu.app.R
import com.google.common.util.concurrent.Futures
import com.google.common.util.concurrent.ListenableFuture
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.launch

/**
 * Foreground MediaSessionService that surfaces the practice session as a
 * system media session, so the user can play/pause from the notification,
 * the lock screen, and Bluetooth/headset transport buttons.
 *
 * The actual practice audio (Morse + spoken answers) is generated by
 * [com.cwjitsu.app.audio.CwAudioEngine], driven by the app-wide
 * [SessionOrchestrator] - NOT by this ExoPlayer. The ExoPlayer plays a
 * short, silent, looping clip purely as a "carrier": Media3 needs a real
 * Player to host the session, post the notification, and receive transport
 * buttons, and the carrier keeps that machinery alive while a session runs.
 *
 * Control flow is a single loop with the orchestrator as source of truth:
 *  - orchestrator state  ->  carrier playWhenReady   (mirrored by the collector)
 *  - transport button    ->  carrier playWhenReady   (Media3 default commands)
 *                        ->  orchestrator.resume()/pause()  (the Player.Listener)
 * orchestrator.resume()/pause() are idempotent, so the mirror never fights
 * the listener.
 *
 * Previous/Next transport buttons don't touch the carrier at all: the
 * session is built on a [ForwardingPlayer] wrapper that force-advertises
 * the seek-to-previous/next commands (so the notification and lock screen
 * show the buttons) and forwards them straight to the orchestrator's
 * previous()/skip().
 */
@UnstableApi
class PlaybackService : MediaSessionService() {

    private var player: ExoPlayer? = null
    private var session: MediaSession? = null
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main)

    private val app: CWJitsuApp get() = application as CWJitsuApp

    override fun onCreate() {
        super.onCreate()
        val audioAttrs = MediaAudioAttributes.Builder()
            .setUsage(C.USAGE_MEDIA)
            .setContentType(C.AUDIO_CONTENT_TYPE_SONIFICATION)
            .build()
        val ep = ExoPlayer.Builder(this).build().apply {
            // The carrier doubles as the app's audio-focus owner: the CW
            // engine writes raw PCM and never requests focus itself, so
            // without this the practice audio would just mix over whatever
            // else is playing (music, navigation). ExoPlayer requests focus
            // when the carrier starts and pauses it on focus loss, which the
            // Player.Listener below forwards to the orchestrator - so
            // another app taking over audio pauses the practice session
            // instead of talking over it.
            setAudioAttributes(audioAttrs, /* handleAudioFocus = */ true)
            volume = 0f
            repeatMode = Player.REPEAT_MODE_ONE
            playWhenReady = false
        }
        ep.addListener(object : Player.Listener {
            override fun onPlayWhenReadyChanged(playWhenReady: Boolean, reason: Int) {
                // A transport button (notification / Bluetooth / lock screen)
                // toggles the carrier; forward that to the orchestrator. Both
                // calls no-op when the state already matches, so our own
                // mirroring writes below don't loop back.
                if (playWhenReady) app.orchestrator.resume() else app.orchestrator.pause()
            }
        })
        player = ep

        // The carrier has a single looping media item, so ExoPlayer never
        // advertises seek-to-previous/next on its own. Force the commands on
        // and reroute them to the orchestrator so the notification / lock
        // screen / Bluetooth prev-next buttons drive the practice session.
        val transportPlayer = object : ForwardingPlayer(ep) {
            override fun getAvailableCommands(): Player.Commands =
                super.getAvailableCommands().buildUpon()
                    .addAll(
                        Player.COMMAND_SEEK_TO_PREVIOUS,
                        Player.COMMAND_SEEK_TO_PREVIOUS_MEDIA_ITEM,
                        Player.COMMAND_SEEK_TO_NEXT,
                        Player.COMMAND_SEEK_TO_NEXT_MEDIA_ITEM,
                    )
                    .build()

            override fun isCommandAvailable(command: Int): Boolean =
                when (command) {
                    Player.COMMAND_SEEK_TO_PREVIOUS,
                    Player.COMMAND_SEEK_TO_PREVIOUS_MEDIA_ITEM,
                    Player.COMMAND_SEEK_TO_NEXT,
                    Player.COMMAND_SEEK_TO_NEXT_MEDIA_ITEM,
                    -> true
                    else -> super.isCommandAvailable(command)
                }

            override fun seekToPrevious() = app.orchestrator.previous()
            override fun seekToPreviousMediaItem() = app.orchestrator.previous()
            override fun seekToNext() = app.orchestrator.skip()
            override fun seekToNextMediaItem() = app.orchestrator.skip()
        }

        // Custom Stop action: unlike pause, Stop tears the practice session
        // down entirely, which (via the mirror collector below) clears the
        // carrier and dismisses the notification.
        val stopButton = CommandButton.Builder()
            .setDisplayName("Stop")
            .setIconResId(R.drawable.ic_stop)
            .setSessionCommand(SessionCommand(ACTION_STOP_SESSION, Bundle.EMPTY))
            .build()

        session = MediaSession.Builder(this, transportPlayer)
            .setCallback(PlaybackCallback(onStopSession = { app.orchestrator.stop() }))
            .setCustomLayout(listOf(stopButton))
            .build()

        // Mirror the orchestrator's state onto the carrier so the media
        // session reflects what the practice session is actually doing.
        scope.launch {
            combine(app.orchestrator.runnerState, app.orchestrator.paused) { state, paused ->
                state to paused
            }.collect { (state, paused) ->
                val p = player ?: return@collect
                if (state == SessionOrchestrator.RunnerState.RUNNING) {
                    ensureCarrierLoaded(p)
                    p.playWhenReady = !paused
                } else {
                    // Session ended: drop the carrier so the notification
                    // goes away rather than lingering as a dead "paused".
                    p.playWhenReady = false
                    p.clearMediaItems()
                }
            }
        }
    }

    private fun ensureCarrierLoaded(p: ExoPlayer) {
        if (p.mediaItemCount > 0) return
        val item = MediaItem.Builder()
            .setUri("android.resource://$packageName/${R.raw.silence}")
            .setMediaMetadata(
                MediaMetadata.Builder()
                    .setTitle("CW Jitsu")
                    .setArtist("Morse practice")
                    // App icon as the notification / lock-screen artwork.
                    .setArtworkUri(
                        Uri.parse("android.resource://$packageName/${R.drawable.cwjicon}")
                    )
                    .build()
            )
            .build()
        p.setMediaItem(item)
        p.prepare()
    }

    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession? = session

    override fun onTaskRemoved(rootIntent: Intent?) {
        // If nothing is playing, let the service go when the task is swiped.
        if (player?.playWhenReady != true) stopSelf()
    }

    override fun onDestroy() {
        scope.cancel()
        session?.release()
        player?.release()
        session = null
        player = null
        super.onDestroy()
    }
}

/** Custom session command: fully stop the practice session (not just pause). */
const val ACTION_STOP_SESSION = "com.cwjitsu.app.STOP_SESSION"

/**
 * MediaSession.Callback that accepts controllers and the custom Stop command.
 * Media button events (notification, Bluetooth, lock screen) arrive as the
 * default play/pause player commands and are handled on the carrier's
 * Player.Listener; prev/next arrive on the ForwardingPlayer's seek overrides;
 * the Stop button arrives here as a custom command.
 */
@UnstableApi
class PlaybackCallback(
    private val onStopSession: () -> Unit,
) : MediaSession.Callback {
    override fun onConnect(
        session: MediaSession,
        controller: MediaSession.ControllerInfo,
    ): MediaSession.ConnectionResult {
        val sessionCommands = MediaSession.ConnectionResult.DEFAULT_SESSION_COMMANDS
            .buildUpon()
            .add(SessionCommand(ACTION_STOP_SESSION, Bundle.EMPTY))
            .build()
        return MediaSession.ConnectionResult.accept(
            sessionCommands,
            MediaSession.ConnectionResult.DEFAULT_PLAYER_COMMANDS,
        )
    }

    override fun onCustomCommand(
        session: MediaSession,
        controller: MediaSession.ControllerInfo,
        customCommand: SessionCommand,
        args: Bundle,
    ): ListenableFuture<SessionResult> {
        if (customCommand.customAction == ACTION_STOP_SESSION) {
            onStopSession()
            return Futures.immediateFuture(SessionResult(SessionResult.RESULT_SUCCESS))
        }
        return super.onCustomCommand(session, controller, customCommand, args)
    }
}
